services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
    tty: true
    stdin_open: true

  # Serviço para rodar os testes
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .env 