FROM golang:1.21

WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

# Command to run tests
CMD ["/usr/local/go/bin/go", "test", "-v", "./..."] 